// <auto-generated />
using System;
using System.Collections.Generic;
using ERP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERP.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ErpDbContext))]
    [Migration("20260806102032_DashboardRowLevelSecurity")]
    partial class DashboardRowLevelSecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ERP.Domain.Accounting.AccountGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystemGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_group");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameArabic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_arabic");

                    b.Property<int>("Nature")
                        .HasColumnType("integer")
                        .HasColumnName("nature");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Schedule")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("schedule");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_account_groups");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_account_groups_is_deleted");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_account_groups_parent_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_account_groups_tenant");

                    b.HasIndex("FirmId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_account_groups_firm_code")
                        .HasFilter("is_deleted = false");

                    b.ToTable("account_groups", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Accounting.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BillDate")
                        .HasColumnType("date")
                        .HasColumnName("bill_date");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bill_number");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("OriginVoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_voucher_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OriginalAmount", "ERP.Domain.Accounting.Bill.OriginalAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("original_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SettledAmount", "ERP.Domain.Accounting.Bill.SettledAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("settled_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("settled_currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pk_bills");

                    b.HasIndex("LedgerId")
                        .HasDatabaseName("ix_bills_ledger_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bills_tenant");

                    b.HasIndex("FirmId", "DueDate")
                        .HasDatabaseName("ix_bills_open_by_due_date")
                        .HasFilter("status <> 3");

                    b.HasIndex("FirmId", "LedgerId", "BillNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_bills_party_reference");

                    b.HasIndex("FirmId", "LedgerId", "Status")
                        .HasDatabaseName("ix_bills_open_by_party")
                        .HasFilter("status <> 3");

                    b.ToTable("bills", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Accounting.BillAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AllocatedOn")
                        .HasColumnType("date")
                        .HasColumnName("allocated_on");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "ERP.Domain.Accounting.BillAllocation.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pk_bill_allocations");

                    b.HasIndex("BillId")
                        .HasDatabaseName("ix_bill_allocations_bill_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bill_allocations_tenant");

                    b.HasIndex("VoucherId")
                        .HasDatabaseName("ix_bill_allocations_voucher");

                    b.ToTable("bill_allocations", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Accounting.Cheque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BankLedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_ledger_id");

                    b.Property<string>("ChequeNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cheque_number");

                    b.Property<Guid?>("ClearingVoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("clearing_voucher_id");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("date")
                        .HasColumnName("closed_on");

                    b.Property<string>("ClosureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("closure_reason");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DepositedOn")
                        .HasColumnType("date")
                        .HasColumnName("deposited_on");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<string>("DrawnOnBank")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("drawn_on_bank");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<DateOnly>("InstrumentDate")
                        .HasColumnType("date")
                        .HasColumnName("instrument_date");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("OriginVoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_voucher_id");

                    b.Property<Guid>("PartyLedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_ledger_id");

                    b.Property<DateOnly>("RecordedOn")
                        .HasColumnType("date")
                        .HasColumnName("recorded_on");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "ERP.Domain.Accounting.Cheque.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pk_cheques");

                    b.HasIndex("BankLedgerId")
                        .HasDatabaseName("ix_cheques_bank_ledger_id");

                    b.HasIndex("ClearingVoucherId")
                        .HasDatabaseName("ix_cheques_clearing_voucher_id");

                    b.HasIndex("OriginVoucherId")
                        .HasDatabaseName("ix_cheques_origin_voucher_id");

                    b.HasIndex("PartyLedgerId")
                        .HasDatabaseName("ix_cheques_party_ledger_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_cheques_tenant");

                    b.HasIndex("FirmId", "InstrumentDate")
                        .HasDatabaseName("ix_cheques_open_by_due_date")
                        .HasFilter("status < 3");

                    b.HasIndex("FirmId", "PartyLedgerId")
                        .HasDatabaseName("ix_cheques_by_party");

                    b.HasIndex("FirmId", "RecordedOn")
                        .HasDatabaseName("ix_cheques_by_recorded_date");

                    b.HasIndex("FirmId", "BankLedgerId", "ChequeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_cheques_issued_number")
                        .HasFilter("direction = 2 AND status < 3");

                    b.HasIndex("FirmId", "PartyLedgerId", "ChequeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_cheques_received_number")
                        .HasFilter("direction = 1 AND status < 3");

                    b.ToTable("cheques", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Accounting.Ledger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_group_id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int?>("CreditDays")
                        .HasColumnType("integer")
                        .HasColumnName("credit_days");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("credit_limit");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBillWise")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bill_wise");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mobile_number");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameArabic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_arabic");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("opening_balance");

                    b.Property<int>("OpeningBalanceSide")
                        .HasColumnType("integer")
                        .HasColumnName("opening_balance_side");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("StateCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("state_code");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_registration_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_ledgers");

                    b.HasIndex("AccountGroupId")
                        .HasDatabaseName("ix_ledgers_account_group_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_ledgers_is_deleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_ledgers_tenant");

                    b.HasIndex("FirmId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_ledgers_firm_code")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("FirmId", "Kind")
                        .HasDatabaseName("ix_ledgers_firm_kind");

                    b.HasIndex("FirmId", "MobileNumber")
                        .HasDatabaseName("ix_ledgers_firm_mobile")
                        .HasFilter("mobile_number IS NOT NULL");

                    b.ToTable("ledgers", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Accounting.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("base_currency")
                        .IsFixedLength();

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(19, 8)
                        .HasColumnType("numeric(19,8)")
                        .HasColumnName("exchange_rate");

                    b.Property<Guid>("FinancialYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("financial_year_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Narration")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("narration");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.Property<string>("PaymentMode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payment_mode");

                    b.Property<DateTimeOffset?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at_utc");

                    b.Property<Guid?>("PostedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_by");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_vouchers");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_vouchers_is_deleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_vouchers_tenant");

                    b.HasIndex("FirmId", "Date", "Status")
                        .HasDatabaseName("ix_vouchers_firm_date_status");

                    b.HasIndex("BranchId", "FinancialYearId", "Type", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_vouchers_branch_year_type_number")
                        .HasFilter("is_deleted = false");

                    b.ToTable("vouchers", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Accounting.VoucherLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("Narration")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("narration");

                    b.Property<int>("Side")
                        .HasColumnType("integer")
                        .HasColumnName("side");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "ERP.Domain.Accounting.VoucherLine.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BaseAmount", "ERP.Domain.Accounting.VoucherLine.BaseAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("base_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("base_currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pk_voucher_lines");

                    b.HasIndex("LedgerId")
                        .HasDatabaseName("ix_voucher_lines_ledger");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_voucher_lines_tenant");

                    b.HasIndex("VoucherId")
                        .HasDatabaseName("ix_voucher_lines_voucher_id");

                    b.ToTable("voucher_lines", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource");

                    b.Property<int>("Verb")
                        .HasColumnType("integer")
                        .HasColumnName("verb");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_code");

                    b.HasIndex("Module")
                        .HasDatabaseName("ix_permissions_module");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<int>("RevocationReason")
                        .HasColumnType("integer")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_hash");

                    b.HasIndex("UserId", "RevokedAtUtc")
                        .HasDatabaseName("ix_refresh_tokens_user_active");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<Guid?>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<bool>("GrantsAllPermissions")
                        .HasColumnType("boolean")
                        .HasColumnName("grants_all_permissions");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_role");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_roles_is_deleted");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_tenant_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_role_permissions_tenant");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<DateTimeOffset?>("LockedOutUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_out_until_utc");

                    b.Property<int>("MfaMethod")
                        .HasColumnType("integer")
                        .HasColumnName("mfa_method");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mobile_number");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<DateTimeOffset?>("PasswordChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("totp_secret");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_users_is_deleted");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_email")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("TenantId", "UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_username")
                        .HasFilter("is_deleted = false");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Identity.UserFirmAccess", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("UserId", "FirmId", "BranchId")
                        .HasName("pk_user_firm_access");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_firm_access_tenant");

                    b.ToTable("user_firm_access", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_roles_tenant");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Numbering.NumberingSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("document_type");

                    b.Property<Guid?>("FinancialYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("financial_year_id");

                    b.Property<string>("FinancialYearLabel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("financial_year_label");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int>("NextNumber")
                        .HasColumnType("integer")
                        .HasColumnName("next_number");

                    b.Property<int>("NumberLength")
                        .HasColumnType("integer")
                        .HasColumnName("number_length");

                    b.Property<string>("Prefix")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prefix");

                    b.Property<string>("Separator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("separator");

                    b.Property<int>("StartingNumber")
                        .HasColumnType("integer")
                        .HasColumnName("starting_number");

                    b.Property<string>("Suffix")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("suffix");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_numbering_series");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_numbering_series_tenant");

                    b.HasIndex("FirmId", "DocumentType", "BranchId", "FinancialYearId")
                        .IsUnique()
                        .HasDatabaseName("ix_numbering_series_scope");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("FirmId", "DocumentType", "BranchId", "FinancialYearId"), false);

                    b.ToTable("numbering_series", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Platform.Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NameArabic")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_arabic");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_dashboards");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_dashboards_tenant");

                    b.HasIndex("FirmId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_dashboards_code");

                    b.ToTable("dashboards", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Platform.DashboardRole", b =>
                {
                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("dashboard_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("DashboardId", "RoleId")
                        .HasName("pk_dashboard_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_dashboard_roles_role");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_dashboard_roles_tenant");

                    b.ToTable("dashboard_roles", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Platform.DashboardWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("dashboard_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("metric_code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Span")
                        .HasColumnType("integer")
                        .HasColumnName("span");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<string>("TitleArabic")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title_arabic");

                    b.HasKey("Id")
                        .HasName("pk_dashboard_widgets");

                    b.HasIndex("DashboardId")
                        .HasDatabaseName("ix_dashboard_widgets_dashboard_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_dashboard_widgets_tenant");

                    b.ToTable("dashboard_widgets", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Platform.GridLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("GridKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("grid_key");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_grid_layouts");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_grid_layouts_tenant");

                    b.HasIndex("UserId", "GridKey")
                        .IsUnique()
                        .HasDatabaseName("ix_grid_layouts_user_grid");

                    b.ToTable("grid_layouts", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Platform.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("LabelArabic")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label_arabic");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("RequiredPermission")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("required_permission");

                    b.Property<string>("Route")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("route");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_menu_items");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_menu_items_parent_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_menu_items_tenant");

                    b.HasIndex("FirmId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_menu_items_code");

                    b.HasIndex("FirmId", "ParentId", "SortOrder")
                        .HasDatabaseName("ix_menu_items_tree");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Tenancy.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsHeadOffice")
                        .HasColumnType("boolean")
                        .HasColumnName("is_head_office");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameArabic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_arabic");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasIndex("FirmId")
                        .IsUnique()
                        .HasDatabaseName("ix_branches_single_head_office")
                        .HasFilter("is_head_office = true AND is_deleted = false");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_branches_is_deleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_branches_tenant");

                    b.HasIndex("FirmId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_branches_firm_code")
                        .HasFilter("is_deleted = false");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Tenancy.FinancialYear", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_financial_years");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_financial_years_tenant");

                    b.HasIndex("FirmId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_financial_years_firm_code");

                    b.HasIndex("FirmId", "StartDate", "EndDate")
                        .HasDatabaseName("ix_financial_years_firm_range");

                    b.ToTable("financial_years", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Tenancy.Firm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("base_currency")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameArabic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_arabic");

                    b.Property<string>("StateCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("state_code");

                    b.Property<int>("TaxRegime")
                        .HasColumnType("integer")
                        .HasColumnName("tax_regime");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_registration_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_firms");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_firms_is_deleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_firms_tenant");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_firms_tenant_code")
                        .HasFilter("is_deleted = false");

                    b.ToTable("firms", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("SubscriptionEndsOn")
                        .HasColumnType("date")
                        .HasColumnName("subscription_ends_on");

                    b.Property<int>("SubscriptionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_code");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Accounting.AccountGroup", b =>
                {
                    b.HasOne("ERP.Domain.Accounting.AccountGroup", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_account_groups_account_groups_parent_id");
                });

            modelBuilder.Entity("ERP.Domain.Accounting.Bill", b =>
                {
                    b.HasOne("ERP.Domain.Accounting.Ledger", null)
                        .WithMany()
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bills_ledgers_ledger_id");
                });

            modelBuilder.Entity("ERP.Domain.Accounting.BillAllocation", b =>
                {
                    b.HasOne("ERP.Domain.Accounting.Bill", null)
                        .WithMany("Allocations")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bill_allocations_bills_bill_id");

                    b.HasOne("ERP.Domain.Accounting.Voucher", null)
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bill_allocations_vouchers_voucher_id");
                });

            modelBuilder.Entity("ERP.Domain.Accounting.Cheque", b =>
                {
                    b.HasOne("ERP.Domain.Accounting.Ledger", null)
                        .WithMany()
                        .HasForeignKey("BankLedgerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cheques_ledgers_bank_ledger_id");

                    b.HasOne("ERP.Domain.Accounting.Voucher", null)
                        .WithMany()
                        .HasForeignKey("ClearingVoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cheques_vouchers_clearing_voucher_id");

                    b.HasOne("ERP.Domain.Accounting.Voucher", null)
                        .WithMany()
                        .HasForeignKey("OriginVoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cheques_vouchers_origin_voucher_id");

                    b.HasOne("ERP.Domain.Accounting.Ledger", null)
                        .WithMany()
                        .HasForeignKey("PartyLedgerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cheques_ledgers_party_ledger_id");
                });

            modelBuilder.Entity("ERP.Domain.Accounting.Ledger", b =>
                {
                    b.HasOne("ERP.Domain.Accounting.AccountGroup", null)
                        .WithMany()
                        .HasForeignKey("AccountGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledgers_account_groups_account_group_id");
                });

            modelBuilder.Entity("ERP.Domain.Accounting.VoucherLine", b =>
                {
                    b.HasOne("ERP.Domain.Accounting.Ledger", null)
                        .WithMany()
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_voucher_lines_ledgers_ledger_id");

                    b.HasOne("ERP.Domain.Accounting.Voucher", null)
                        .WithMany("Lines")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_voucher_lines_vouchers_voucher_id");
                });

            modelBuilder.Entity("ERP.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("ERP.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("ERP.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("ERP.Domain.Identity.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("ERP.Domain.Identity.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("ERP.Domain.Identity.UserFirmAccess", b =>
                {
                    b.HasOne("ERP.Domain.Identity.User", null)
                        .WithMany("FirmAccess")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_firm_access_users_user_id");
                });

            modelBuilder.Entity("ERP.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("ERP.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("ERP.Domain.Identity.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("ERP.Domain.Platform.DashboardRole", b =>
                {
                    b.HasOne("ERP.Domain.Platform.Dashboard", null)
                        .WithMany("Roles")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dashboard_roles_dashboards_dashboard_id");

                    b.HasOne("ERP.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dashboard_roles_roles_role_id");
                });

            modelBuilder.Entity("ERP.Domain.Platform.DashboardWidget", b =>
                {
                    b.HasOne("ERP.Domain.Platform.Dashboard", null)
                        .WithMany("Widgets")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dashboard_widgets_dashboards_dashboard_id");
                });

            modelBuilder.Entity("ERP.Domain.Platform.GridLayout", b =>
                {
                    b.HasOne("ERP.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grid_layouts_users_user_id");
                });

            modelBuilder.Entity("ERP.Domain.Platform.MenuItem", b =>
                {
                    b.HasOne("ERP.Domain.Platform.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_menu_items_menu_items_parent_id");
                });

            modelBuilder.Entity("ERP.Domain.Tenancy.Branch", b =>
                {
                    b.HasOne("ERP.Domain.Tenancy.Firm", null)
                        .WithMany("Branches")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_branches_firms_firm_id");
                });

            modelBuilder.Entity("ERP.Domain.Accounting.Bill", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("ERP.Domain.Accounting.Voucher", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("ERP.Domain.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ERP.Domain.Identity.User", b =>
                {
                    b.Navigation("FirmAccess");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ERP.Domain.Platform.Dashboard", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Widgets");
                });

            modelBuilder.Entity("ERP.Domain.Tenancy.Firm", b =>
                {
                    b.Navigation("Branches");
                });
#pragma warning restore 612, 618
        }
    }
}
